# Generated by Django 6.1.1 on 2026-09-15 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WYR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='scenario_question',
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_question_1',
            field=models.CharField(default=datetime.datetime(2026, 9, 15, 19, 24, 46, 405933, tzinfo=datetime.timezone.utc), max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_question_2',
            field=models.CharField(default=datetime.datetime(2026, 9, 15, 19, 25, 6, 795377, tzinfo=datetime.timezone.utc), max_length=75),
            preserve_default=False,
        ),
    ]
