# Generated by Django 6.1.1 on 2026-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WYR', '0002_remove_scenario_scenario_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='votes',
            new_name='votesQ1',
        ),
        migrations.AddField(
            model_name='scenario',
            name='votesQ2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_question_1',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_question_2',
            field=models.CharField(default='', max_length=75),
        ),
    ]
